#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the FluentMappingGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Telerik.OpenAccess.Metadata.Relational;

namespace ItShop.MySql
{

	public partial class ItShopMySqlMetadataSource : FluentMetadataSource
	{
		
		protected override IList<MappingConfiguration> PrepareMapping()
		{
			List<MappingConfiguration> mappingConfigurations = new List<MappingConfiguration>();
           
            var productMapping = new MappingConfiguration<ProductMySql>();
            productMapping.MapType(product => new
            {
                ProductId = product.ProductID,
                ProductName = product.ProductName,
                BuyingPrice = product.BuyingPrice,
                BasePrice = product.BasePrice,
                ManufacturerId = product.ManufacturerId,
                CategoryId = product.CategoryId
            }).ToTable("EntityTest");
            productMapping.HasProperty(p => p.ProductID).IsIdentity();

            mappingConfigurations.Add(productMapping);
			return mappingConfigurations;
		}
		
		protected override void SetContainerSettings(MetadataContainer container)
		{
			container.Name = "ItShopMySql";
			container.DefaultNamespace = "ItShop.MySql";
			container.NameGenerator.SourceStrategy = Telerik.OpenAccess.Metadata.NamingSourceStrategy.Property;
			container.NameGenerator.RemoveCamelCase = false;
		}
	}
}
#pragma warning restore 1591
