#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the FluentMappingGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Telerik.OpenAccess.Metadata.Relational;
using ItShop.Model;

namespace ItShop.Data.MySQL
{

	public partial class ItShopMetadataSource : FluentMetadataSource
	{
		
		protected override IList<MappingConfiguration> PrepareMapping()
		{
			List<MappingConfiguration> mappingConfigurations = new List<MappingConfiguration>();

            var productMapping = new MappingConfiguration<Product>();
            productMapping.MapType(product => new
            {
                ProductId = product.ProductId,
                ProductName = product.ProductName,
                BuyingPrice = product.BuyingPrice,
                BasePrice = product.BasePrice,
                ManufacturerId = product.ManufacturerId,
                CategoryId = product.CategoryId
            }).ToTable("EntityTest");
            productMapping.HasProperty(p => p.ProductId).IsIdentity();

            mappingConfigurations.Add(productMapping);

			return mappingConfigurations;
		}
		
		protected override void SetContainerSettings(MetadataContainer container)
		{
			container.Name = "ItShop";
			container.DefaultNamespace = "ItShop.Data.MySQL";
			container.NameGenerator.SourceStrategy = Telerik.OpenAccess.Metadata.NamingSourceStrategy.Property;
			container.NameGenerator.RemoveCamelCase = false;
		}
	}
}
#pragma warning restore 1591
